export const mockUsers = [
  { id: "1", name: "John Smith", role: "engineer" },
  { id: "2", name: "Sarah Johnson", role: "engineer" },
  { id: "3", name: "Michael Chen", role: "engineer" },
  { id: "4", name: "Emily Davis", role: "manager" },
  { id: "5", name: "Current User", role: "engineer" },
];

export const mockTemplates = [
  {
    id: "1",
    name: "Charging Station Inspection",
    description: "Standard inspection procedure for charging stations",
    steps: [
      {
        id: "step1",
        name: "Pre-Inspection",
        description: "Verify location and identity",
        order: 1,
        fields: [
          { id: "field1", name: "Technician Face Recognition", type: "faceRecognition", required: true },
          { id: "field2", name: "Station Location", type: "location", required: true },
          { id: "field3", name: "Station Photo", type: "photo", required: true },
        ],
      },
      {
        id: "step2",
        name: "Physical Inspection",
        description: "Check physical condition of the station",
        order: 2,
        fields: [
          { id: "field4", name: "Exterior Condition", type: "text", required: true },
          { id: "field5", name: "Damage Assessment", type: "text", required: false },
          { id: "field6", name: "Damage Photos", type: "photo", required: false },
        ],
      },
      {
        id: "step3",
        name: "Electrical Testing",
        description: "Test electrical components",
        order: 3,
        fields: [
          { id: "field7", name: "Voltage Reading", type: "number", required: true },
          { id: "field8", name: "Current Reading", type: "number", required: true },
          { id: "field9", name: "Test Results Photo", type: "photo", required: true },
        ],
      },
      {
        id: "step4",
        name: "Completion",
        description: "Finalize inspection",
        order: 4,
        fields: [
          { id: "field10", name: "Overall Status", type: "text", required: true },
          { id: "field11", name: "Technician Signature", type: "signature", required: true },
          { id: "field12", name: "Completion Time", type: "date", required: true },
        ],
      },
    ],
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-01-15"),
  },
  {
    id: "2",
    name: "Emergency Repair",
    description: "Emergency repair protocol",
    steps: [
      {
        id: "step1",
        name: "Incident Documentation",
        description: "Document the emergency",
        order: 1,
        fields: [
          { id: "field1", name: "Face Recognition", type: "faceRecognition", required: true },
          { id: "field2", name: "Emergency Location", type: "location", required: true },
          { id: "field3", name: "Incident Photo", type: "photo", required: true },
          { id: "field4", name: "Issue Description", type: "text", required: true },
        ],
      },
      {
        id: "step2",
        name: "Repair Work",
        description: "Perform the repair",
        order: 2,
        fields: [
          { id: "field5", name: "Parts Used", type: "text", required: true },
          { id: "field6", name: "Repair Notes", type: "text", required: true },
          { id: "field7", name: "After Repair Photo", type: "photo", required: true },
        ],
      },
      {
        id: "step3",
        name: "Sign-off",
        description: "Complete the repair",
        order: 3,
        fields: [
          { id: "field8", name: "Signature", type: "signature", required: true },
          { id: "field9", name: "Completion Date", type: "date", required: true },
        ],
      },
    ],
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-01-20"),
  },
  {
    id: "3",
    name: "Routine Maintenance",
    description: "Monthly routine maintenance checklist",
    steps: [
      {
        id: "step1",
        name: "Arrival Check",
        description: "Initial arrival verification",
        order: 1,
        fields: [
          { id: "field1", name: "Face Recognition", type: "faceRecognition", required: true },
          { id: "field2", name: "Location Verification", type: "location", required: true },
        ],
      },
      {
        id: "step2",
        name: "Maintenance Tasks",
        description: "Perform maintenance",
        order: 2,
        fields: [
          { id: "field3", name: "Cleaning Status", type: "text", required: true },
          { id: "field4", name: "Cable Inspection", type: "text", required: true },
          { id: "field5", name: "Software Version", type: "text", required: true },
          { id: "field6", name: "Before Photo", type: "photo", required: true },
          { id: "field7", name: "After Photo", type: "photo", required: true },
        ],
      },
    ],
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-01-10"),
  },
];

export const mockTickets = [
  {
    id: "T001",
    title: "Charging Station A1 - Inspection",
    description: "Monthly inspection for station A1 at Central Plaza",
    templateId: "1",
    templateName: "Charging Station Inspection",
    status: "new",
    priority: "medium",
    assignedTo: "1",
    assignedToName: "John Smith",
    createdBy: "4",
    createdByName: "Emily Davis",
    createdAt: new Date("2025-10-28"),
    dueDate: new Date("2025-11-05"),
    completedSteps: [],
    stepData: {},
    accepted: false,
    comments: [],
  },
  {
    id: "T002",
    title: "Station B5 - Power Failure",
    description: "Station B5 reported complete power failure",
    templateId: "2",
    templateName: "Emergency Repair",
    status: "assigned",
    priority: "urgent",
    assignedTo: "5",
    assignedToName: "Current User",
    createdBy: "4",
    createdByName: "Emily Davis",
    createdAt: new Date("2025-10-29"),
    dueDate: new Date("2025-10-30"),
    completedSteps: [],
    stepData: {},
    accepted: false,
    comments: [],
  },
  {
    id: "T003",
    title: "Station C2 - Monthly Maintenance",
    description: "Routine monthly maintenance for station C2",
    templateId: "3",
    templateName: "Routine Maintenance",
    status: "inProgress",
    priority: "low",
    assignedTo: "5",
    assignedToName: "Current User",
    createdBy: "4",
    createdByName: "Emily Davis",
    createdAt: new Date("2025-10-27"),
    dueDate: new Date("2025-11-01"),
    completedSteps: ["step1"],
    stepData: {
      step1: {
        field1: "Verified",
        field2: "13.7563° N, 100.5018° E",
      },
    },
    accepted: true,
    acceptedAt: new Date("2025-10-27"),
    comments: [
      {
        id: "C1",
        userId: "5",
        userName: "Current User",
        comment: "Accepted and started work",
        createdAt: new Date("2025-10-27"),
        type: "accept",
      },
    ],
  },
  {
    id: "T004",
    title: "Station D3 - Cable Damage",
    description: "Cable damage reported at station D3",
    templateId: "2",
    templateName: "Emergency Repair",
    status: "inProgress",
    priority: "high",
    assignedTo: "2",
    assignedToName: "Sarah Johnson",
    createdBy: "4",
    createdByName: "Emily Davis",
    createdAt: new Date("2025-10-26"),
    dueDate: new Date("2025-10-31"),
    completedSteps: ["step1"],
    stepData: {},
    accepted: true,
    acceptedAt: new Date("2025-10-26"),
    comments: [],
  },
  {
    id: "T005",
    title: "Station E1 - Inspection Complete",
    description: "Completed inspection for station E1",
    templateId: "1",
    templateName: "Charging Station Inspection",
    status: "done",
    priority: "medium",
    assignedTo: "3",
    assignedToName: "Michael Chen",
    createdBy: "4",
    createdByName: "Emily Davis",
    createdAt: new Date("2025-10-20"),
    dueDate: new Date("2025-10-25"),
    completedSteps: ["step1", "step2", "step3", "step4"],
    stepData: {},
    accepted: true,
    acceptedAt: new Date("2025-10-20"),
    comments: [],
  },
  {
    id: "T006",
    title: "Station F2 - New Installation Check",
    description: "Initial inspection for newly installed station F2",
    templateId: "1",
    templateName: "Charging Station Inspection",
    status: "new",
    priority: "high",
    assignedTo: "1",
    assignedToName: "John Smith",
    createdBy: "4",
    createdByName: "Emily Davis",
    createdAt: new Date("2025-10-29"),
    dueDate: new Date("2025-11-02"),
    completedSteps: [],
    stepData: {},
    accepted: false,
    comments: [],
  },
  {
    id: "T007",
    title: "Station G4 - Routine Check",
    description: "Monthly routine maintenance",
    templateId: "3",
    templateName: "Routine Maintenance",
    status: "done",
    priority: "low",
    assignedTo: "5",
    assignedToName: "Current User",
    createdBy: "4",
    createdByName: "Emily Davis",
    createdAt: new Date("2025-10-15"),
    dueDate: new Date("2025-10-22"),
    completedSteps: ["step1", "step2"],
    stepData: {},
    accepted: true,
    acceptedAt: new Date("2025-10-15"),
    comments: [],
  },
];
